from enum import Enum

class ProtocolVersion(Enum):
    V1 = 1

class ActionType(str, Enum):
    SHARE_TEXT = "SHARE_TEXT"
    REMOTE_CMD = "REMOTE_CMD"
    FILE_TRANSFER_META = "FILE_TRANSFER_META"
    FILE_TRANSFER_CHUNK = "FILE_TRANSFER_CHUNK"
    EDIT_MSG = "EDIT_MSG"
    REMOTE_BASH_CMD = "REMOTE_BASH_CMD"
    PING_NODE = "PING_NODE"
    TERM_INIT = "TERM_INIT"
    TERM_AUTH = "TERM_AUTH"
    TERM_STDIN = "TERM_STDIN"
    TERM_STDOUT = "TERM_STDOUT"
    TERM_RESIZE = "TERM_RESIZE"
    TERM_CLOSE = "TERM_CLOSE"
    PAIRING_REQ = "PAIRING_REQ"
    PAIRING_RESP = "PAIRING_RESP"
    
class PeerRole(str, Enum):
    SENDER = "SENDER"
    RECEIVER = "RECEIVER"
